In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/week1.csv')

In [10]:
taille = 30
idx = 5

In [24]:
data = ['CHFJPY-Open', 'CHFJPY-High', 'CHFJPY-Low', 'CHFJPY-Close', 
        'EURCHF-Open', 'EURCHF-High', 'EURCHF-Low', 'EURCHF-Close', 
        'EURJPY-Open', 'EURJPY-High', 'EURJPY-Low', 'EURJPY-Close', 
        'EURUSD-Open', 'EURUSD-High', 'EURUSD-Low', 'EURUSD-Close', 
        'USDCHF-Open', 'USDCHF-High', 'USDCHF-Low', 'USDCHF-Close', 
        'USDCAD-Open', 'USDCAD-High', 'USDCAD-Low', 'USDCAD-Close']
_df = df[data]

In [29]:
df['EURUSD-Close'].loc[5:60].values

array([0.70094, 0.70329, 0.70329, 0.70329, 0.70329, 0.70329, 0.70329,
       0.704  , 0.70682, 0.704  , 0.70388, 0.70929, 0.70753, 0.70788,
       0.70788, 0.70624, 0.70647, 0.70647, 0.70482, 0.70635, 0.70565,
       0.70706, 0.70706, 0.70541, 0.70553, 0.70588, 0.70553, 0.70659,
       0.70753, 0.70765, 0.70647, 0.70741, 0.70729, 0.70706, 0.70718,
       0.70741, 0.70753, 0.70918, 0.70894, 0.70918, 0.70871, 0.70894,
       0.70871, 0.70835, 0.70847, 0.70859, 0.70906, 0.70859, 0.70835,
       0.708  , 0.70953, 0.71012, 0.70894, 0.71129, 0.71141, 0.71447])

In [23]:
_df.loc[idx:idx+taille].values

array([[0.70106 , 0.70118 , 0.70094 , 0.70094 , 0.63662 , 0.63662 ,
        0.636479, 0.636479, 0.60311 , 0.604   , 0.59767 , 0.59767 ,
        0.58325 , 0.58662 , 0.57987 , 0.58662 , 0.37843 , 0.38114 ,
        0.37843 , 0.38071 , 0.57625 , 0.57898 , 0.57591 , 0.57864 ],
       [0.70071 , 0.70329 , 0.70059 , 0.70329 , 0.636549, 0.643803,
        0.636479, 0.643732, 0.603   , 0.60422 , 0.60278 , 0.60422 ,
        0.56987 , 0.5785  , 0.56963 , 0.57638 , 0.381   , 0.381   ,
        0.381   , 0.381   , 0.57852 , 0.57886 , 0.5775  , 0.5783  ],
       [0.70329 , 0.70329 , 0.70329 , 0.70329 , 0.642746, 0.642746,
        0.639014, 0.64007 , 0.60422 , 0.60433 , 0.60011 , 0.60011 ,
        0.57638 , 0.578   , 0.572   , 0.57787 , 0.38114 , 0.38114 ,
        0.37529 , 0.37529 , 0.57852 , 0.57898 , 0.57716 , 0.57886 ],
       [0.70329 , 0.70341 , 0.70329 , 0.70329 , 0.639577, 0.64007 ,
        0.637746, 0.638099, 0.60011 , 0.60011 , 0.60011 , 0.60011 ,
        0.57763 , 0.58912 , 0.576   , 0.58912

In [36]:
_df.loc[idx:idx+taille-1].values.reshape((31, 6, 4))

array([[[0.58325 , 0.58662 , 0.57987 , 0.58662 ],
        [0.60311 , 0.604   , 0.59767 , 0.59767 ],
        [0.63662 , 0.63662 , 0.636479, 0.636479],
        [0.70106 , 0.70118 , 0.70094 , 0.70094 ],
        [0.37843 , 0.38114 , 0.37843 , 0.38071 ],
        [0.57625 , 0.57898 , 0.57591 , 0.57864 ]],

       [[0.56987 , 0.5785  , 0.56963 , 0.57638 ],
        [0.603   , 0.60422 , 0.60278 , 0.60422 ],
        [0.636549, 0.643803, 0.636479, 0.643732],
        [0.70071 , 0.70329 , 0.70059 , 0.70329 ],
        [0.381   , 0.381   , 0.381   , 0.381   ],
        [0.57852 , 0.57886 , 0.5775  , 0.5783  ]],

       [[0.57638 , 0.578   , 0.572   , 0.57787 ],
        [0.60422 , 0.60433 , 0.60011 , 0.60011 ],
        [0.642746, 0.642746, 0.639014, 0.64007 ],
        [0.70329 , 0.70329 , 0.70329 , 0.70329 ],
        [0.38114 , 0.38114 , 0.37529 , 0.37529 ],
        [0.57852 , 0.57898 , 0.57716 , 0.57886 ]],

       [[0.57763 , 0.58912 , 0.576   , 0.58912 ],
        [0.60011 , 0.60011 , 0.60011 , 0.600