In [1]:
import tensorflow as tf

/home/tientranthuong/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/tientranthuong/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/tientranthuong/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/tientranthuong/.local/lib/python3.6/site-packages/tensorflow/

In [3]:
import pandas as pd
import numpy as np

In [6]:
class data:
    def __init__(self, taille, path):
        self.df = pd.read_csv(path)
        self.len = len(self.df)
        self._df = None
        self.taille = taille
        self.idx = None
    
    def retourner(self):
        full_data = np.array([])
        my_data._df[my_data._df.columns[[2, 3, 4, 5]]].values.transpose()
    
    def get_data(self, idx):
        self.idx = idx
        self._df = self.df.loc[idx:idx+self.taille]
    
    def next_data(self):
        self.idx += 1
        self._df = self.df.loc[self.idx:self.idx+self.taille]

In [ ]:
names = ['EURUSD', 'EURJPY', 'EURCHF', 'CHFJPY', 'USDCHF', 'USDCAD']
actions = ['Open', 'High', 'Low', 'Close']

In [7]:
taille = 30
my_data = data(taille, '../data/week1.csv')

In [17]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv3D(32, kernel_size=(6, 4, 10),
                         activation='relu',
                         input_shape=(6,4,taille,1)))
# model.add(Conv2D(64, (3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))
model.add(tf.keras.layers.Flatten())
# model.add(Dense(128, activation='relu'))
# model.add(Dropout(0.5))
model.add(tf.keras.layers.Dense(30, activation='linear'))

In [20]:
model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.01), loss=tf.keras.losses.mean_squared_error)

In [21]:
my_data.get_data(0)

In [38]:
my_data._df[['EURUSD-Open', 'EURUSD-Close']]

EURUSD-Open  EURUSD-Close
0       0.70059       0.70059
1       0.70071       0.70071
2       0.70071       0.70071
3       0.70188       0.70059
4       0.70071       0.70047
5       0.70106       0.70094
6       0.70071       0.70329
7       0.70329       0.70329
8       0.70329       0.70329
9       0.70329       0.70329
10      0.70329       0.70329
11      0.70329       0.70329
12      0.70365       0.70400
13      0.70376       0.70682
14      0.70671       0.70400
15      0.70400       0.70388
16      0.70388       0.70929
17      0.70941       0.70753
18      0.70753       0.70788
19      0.70800       0.70788
20      0.70918       0.70624
21      0.70635       0.70647
22      0.70635       0.70647
23      0.70671       0.70482
24      0.70471       0.70635
25      0.70635       0.70565
26      0.70612       0.70706
27      0.70682       0.70706
28      0.70694       0.70541
29      0.70541       0.70553
30      0.70576       0.70588

In [54]:
inputs1 = tf.keras.layers.Input(shape=(3, 3, 3))
inputs2 = tf.keras.layers.Input(shape=(3, 1))

In [76]:
lstm = tf.keras.layers.LSTM(1, return_state=True, stateful=True)

In [77]:
lstm1 = lstm(inputs1)
lstm2 = lstm(inputs2)

ValueError: If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the time dimension by passing a `batch_shape` argument to your Input layer.

In [73]:
model1 = tf.keras.models.Model(inputs=inputs1, outputs=lstm1)
model2 = tf.keras.models.Model(inputs=inputs2, outputs=lstm2)

In [79]:
data1 = np.array([0.3]).reshape((1, 1, 1))
data2 = np.array([0.1, 0.2, 0.3]).reshape((1, 3, 1))

In [64]:
data2

array([[[0.1],
        [0.2],
        [0.3]]])

In [74]:
print(model1.predict(data1))

[array([[0.04254624]], dtype=float32), array([[0.04254624]], dtype=float32), array([[0.09092246]], dtype=float32)]


In [75]:
print(model2.predict(data2))

[array([[0.07966903]], dtype=float32), array([[0.07966903]], dtype=float32), array([[0.17273344]], dtype=float32)]


In [157]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.LSTM(units=1, input_shape=(2, 1), return_sequences=True))
# model.add(tf.keras.layers.Flatten(input_shape=(9, 3, 5, 1)))
# model.add(tf.keras.layers.Conv3D(1, (2, 2, 2), input_shape=(9, 3, 5, 1)))
# model.add(tf.keras.layers.MaxPooling3D(1, (3, 3, 3)))
model.add(tf.keras.layers.Dense(1))
model.get_weights()

[array([[-0.43989122,  1.0198317 ,  0.2345376 , -0.9853128 ]],
       dtype=float32),
 array([[-0.22631371, -0.21077521,  0.18028453,  0.93373096]],
       dtype=float32),
 array([0., 1., 0., 0.], dtype=float32),
 array([[0.09340715]], dtype=float32),
 array([0.], dtype=float32)]

In [115]:
data = np.array([
    [
    [[[i] for i in range(5)], [[i] for i in range(5)], [[i] for i in range(5)]] for idx in range(9)
    ]

])
data.shape

(1, 9, 3, 5, 1)

In [160]:
data = np.array([
    [
    [0.2] for idx in range(2)
    ],
    [
    [0.1] for idx in range(2)
    ],
    [
    [50] for idx in range(2)
    ],
    [
    [0.1] for idx in range(2)
    ],
    [
    [0.2] for idx in range(2)
    ],
    [
    [0.1] for idx in range(2)
    ]
])
data.shape

(1, 6, 2, 1)

In [161]:
yhat = model.predict(data)
yhat

ValueError: Error when checking : expected lstm_15_input to have 3 dimensions, but got array with shape (1, 6, 2, 1)

In [139]:
data1 = np.array([
    [
    [0.1] for idx in range(2)
    ]

])
model.predict(data1)

array([[[0.01098005],
        [0.01980429]]], dtype=float32)

In [91]:
for r in range(yhat.shape[1]):
    # print each column in the row
	print([yhat[0,r,c,0] for c in range(yhat.shape[2])])

[0.21195614]
[0.21195614]
[0.21195614]


In [51]:
data = [[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0],
		[0, 0, 0, 1, 1, 0, 0, 0]]
data = np.asarray(data)
data = data.reshape(1, 8, 8, 1)

In [62]:
data.shape

(1, 8, 8, 1)

In [238]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.LSTM(256, input_shape=(50, 1), return_sequences=True))
'''
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(tf.keras.layers.Dense(512, activation='softmax'))
model.add(tf.keras.layers.LSTM(256))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(41, activation='softmax'))'''

"\nmodel.add(tf.keras.layers.Dropout(0.2))\nmodel.add(tf.keras.layers.Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))\nmodel.add(tf.keras.layers.Dense(512, activation='softmax'))\nmodel.add(tf.keras.layers.LSTM(256))\nmodel.add(tf.keras.layers.Dropout(0.2))\nmodel.add(tf.keras.layers.Dense(41, activation='softmax'))"

In [243]:
data = np.random.rand(1, 30, 6, 4, 1)
data.shape

(1, 30, 6, 4, 1)

In [275]:
val_input = tf.keras.layers.Input(shape=(30, 6, 4, 1), name='input')
x1 = tf.keras.layers.Conv3D(128, (3, 1, 1))(val_input)
x2 = tf.keras.layers.Conv3D(128, (2, 2, 1))(x1)
x3 = tf.keras.layers.Conv3D(64, (4, 1, 4))(x2)

x4 = tf.keras.layers.Flatten()(x3)
x5 = tf.keras.layers.Reshape((24, 64*5))(x4)

x6 = tf.keras.layers.LSTM(256, return_sequences=True)(x5)
x7 = tf.keras.layers.Dropout(0.2)(x6)
x8 = tf.keras.layers.Dense(256)(x7)

x9 = tf.keras.layers.LSTM(128)(x8)
x10 = tf.keras.layers.Dropout(0.2)(x9)
x11 = tf.keras.layers.Dense(128)(x10)

x12 = tf.keras.layers.Dense(60)(x11)

model = tf.keras.models.Model(inputs=[val_input], outputs=[x12])

In [276]:
prediction = model.predict(data)
for i in range(len(prediction)):
    print(prediction[i].shape)

(1, 28, 6, 4, 128)
(1, 27, 5, 4, 128)
(1, 24, 5, 1, 64)
(1, 7680)
(1, 24, 320)
(1, 24, 256)
(1, 24, 256)
(1, 24, 256)
(1, 128)
(1, 128)
(1, 128)


In [261]:
model.predict(data)[2]

array([[[[[ 0.06230091, -0.10547049, -0.09920137, ...,  0.158773  ,
            0.07676222, -0.05560432]],

         [[ 0.0848618 , -0.01344655,  0.0109903 , ...,  0.10851505,
            0.01139705, -0.03480304]],

         [[ 0.13866381,  0.03697456,  0.01257679, ...,  0.07371847,
            0.05792394, -0.01559443]],

         [[ 0.05803849,  0.02300492, -0.07295097, ...,  0.0787797 ,
           -0.06770124,  0.01327399]],

         [[ 0.02028048, -0.04913523, -0.06035285, ...,  0.13936706,
            0.01289336, -0.01445553]]],


        [[[ 0.1396205 , -0.01459709, -0.06445882, ...,  0.02305821,
            0.01148574, -0.01857274]],

         [[ 0.08885608, -0.07404861, -0.06345838, ...,  0.06249959,
            0.0135855 , -0.0220026 ]],

         [[ 0.09469137,  0.00680337, -0.04136122, ...,  0.07982942,
            0.05656071,  0.05904547]],

         [[ 0.07404216, -0.02596831, -0.09158958, ...,  0.10510857,
            0.01858789,  0.00278825]],

         [[ 0.02784576, -0

In [260]:
model.predict(data)[4]

array([[[ 0.06230091, -0.10547049, -0.09920137, ...,  0.13936706,
          0.01289336, -0.01445553],
        [ 0.1396205 , -0.01459709, -0.06445882, ...,  0.08086649,
         -0.05878355, -0.03117029],
        [ 0.1580752 ,  0.01880205,  0.03252694, ...,  0.13613546,
         -0.03349314, -0.02772783],
        ...,
        [ 0.08956236, -0.04494876, -0.06309128, ...,  0.1267544 ,
          0.01308053,  0.06392439],
        [ 0.18421623, -0.03487212, -0.03248005, ...,  0.0588003 ,
          0.0246201 ,  0.06458971],
        [ 0.04688612, -0.06691369, -0.02241419, ...,  0.0107514 ,
         -0.03207596, -0.01114861]]], dtype=float32)

In [247]:
model.predict(data)[2].shape

(1, 24, 5, 1, 64)